spring:
  application:
    name: Eureka

server:
  port: 8761
  servlet:
    context-path: /eureka

#  cloud:
#    config:
#      import-check:
#        enabled: false

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
